export const FETCH_USER = 'FETCH_USER';
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const USER_REQUEST_RESET_PASSWORD_INIT = 'USER_REQUEST_RESET_PASSWORD_INIT';
export const USER_REQUEST_RESET_PASSWORD = 'USER_REQUEST_RESET_PASSWORD';
export const USER_REQUEST_RESET_PASSWORD_FINISHED = 'USER_REQUEST_RESET_PASSWORD_FINISHED';
export const API_ERROR = 'API_ERROR';
export const API_ERROR_CLEARED = 'API_ERROR_CLEARED';
